import { describe } from 'vitest';
import { testSingleFile } from '../../test-facility/testers';

describe('node', async () => {
    await testSingleFile(import.meta.url, 'test/case.js', [
        { line: 1, column: 10, ruleId: '@stylistic/semi' },
        { line: 4, column: 1, ruleId: 'vars-on-top' },
        { line: 4, column: 1, ruleId: 'no-var' },
        { line: 4, column: 5, ruleId: 'prefer-destructuring' },
        { line: 4, column: 22, ruleId: '@stylistic/semi' },
        { line: 8, column: 1, ruleId: '@stylistic/indent' },
        {
            line: 8,
            column: 14,
            ruleId: '@stylistic/space-before-function-paren',
        },
        { line: 9, column: 1, ruleId: '@stylistic/indent' },
        { line: 10, column: 1, ruleId: '@stylistic/indent' },
        { line: 11, column: 1, ruleId: '@stylistic/indent' },
        { line: 13, column: 1, ruleId: '@stylistic/indent' },
        { line: 14, column: 1, ruleId: '@stylistic/indent' },
        {
            line: 14,
            column: 9,
            ruleId: '@stylistic/space-before-function-paren',
        },
        { line: 15, column: 1, ruleId: '@stylistic/indent' },
        { line: 16, column: 1, ruleId: '@stylistic/indent' },
        { line: 21, column: 1, ruleId: '@stylistic/indent' },
        { line: 22, column: 1, ruleId: '@stylistic/indent' },
        { line: 23, column: 1, ruleId: '@stylistic/indent' },
        { line: 23, column: 28, ruleId: '@stylistic/comma-dangle' },
        { line: 28, column: 1, ruleId: '@stylistic/indent' },
        { line: 38, column: 7, ruleId: 'prefer-destructuring' },
        { line: 39, column: 1, ruleId: 'padding-line-between-statements' },
        { line: 44, column: 1, ruleId: 'padding-line-between-statements' },
        { line: 48, column: 1, ruleId: '@stylistic/indent' },
        { line: 49, column: 1, ruleId: '@stylistic/indent' },
        { line: 51, column: 1, ruleId: '@stylistic/indent' },
        { line: 51, column: 3, ruleId: 'no-console' },
        { line: 57, column: 1, ruleId: 'padding-line-between-statements' },
        { line: 61, column: 1, ruleId: '@stylistic/indent' },
        { line: 64, column: 1, ruleId: 'one-var' },
        { line: 64, column: 8, ruleId: 'one-var-declaration-per-line' },
        { line: 64, column: 11, ruleId: 'one-var-declaration-per-line' },
        { line: 64, column: 13, ruleId: '@stylistic/no-multi-spaces' },
        { line: 64, column: 16, ruleId: 'one-var-declaration-per-line' },
        { line: 64, column: 18, ruleId: '@stylistic/no-multi-spaces' },
        { line: 64, column: 21, ruleId: 'one-var-declaration-per-line' },
        { line: 64, column: 24, ruleId: '@stylistic/semi' },
        { line: 69, column: 1, ruleId: '@stylistic/indent' },
        { line: 70, column: 1, ruleId: '@stylistic/indent' },
        { line: 70, column: 16, ruleId: '@stylistic/semi' },
        { line: 71, column: 1, ruleId: '@stylistic/indent' },
        { line: 74, column: 1, ruleId: 'no-undef' },
    ]);
});
