name: Reusable Lint Workflow

on:
  workflow_call:
    inputs:
      fixErrors:
        required: true
        type: boolean
      nodeVersion:
        required: true
        type: string

jobs:
  lint:
    runs-on: self-runner-node16
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint files
        if: ${{ !inputs.fixErrors }}
        run: pnpm lint

      - name: Lint files for development branch
        if: ${{ inputs.fixErrors }}
        run: pnpm lint:fix

      - name: Commit auto-fixes
        if: |
          always() &&
          ${{ inputs.fixErrors }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Files linted"
