name: Reusable Lint Workflow

on:
  workflow_call:
    inputs:
      isPrimalBranch:
        required: true
        type: boolean
      isPrimaryVersion:
        required: true
        type: boolean
      nodeVersion:
        required: true
        type: string

jobs:
  lint:
    runs-on: self-runner-node16
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Find PR
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        if: inputs.isPrimalBranch == 'false'
        id: prDetails
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          filterOutClosed: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint files
        if: |
          ${{ !inputs.isPrimaryVersion }} ||
          inputs.isPrimalBranch == 'true'
        run: pnpm lint

      - name: Lint files for PR
        if: |
          inputs.isPrimaryVersion &&
          inputs.isPrimalBranch == 'false'
        run: pnpm lint:fix

      - name: Commit auto-fixes
        if: |
          always() &&
          inputs.isPrimaryVersion &&
          inputs.isPrimalBranch == 'false'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Files linted"
