name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      nodeVersion:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test files
        run: pnpm test:ci
