name: Reusable Lint Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  lint:
    runs-on: self-runner-node16
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
            ref: develop

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Lookup for changed logic files
        id: filteredChanges
        run: echo "files=$(git diff-tree --diff-filter=ACM --no-commit-id --name-only -r origin/develop..$(git rev-parse HEAD) . | grep -iE '\.(([mc]?j|t)s|json)$' | xargs)" >> $GITHUB_OUTPUT

      - if: steps.filteredChanges.outputs.files == ''
        run: echo "The branch doesn't contain logic files. Passing on linting..." >> $GITHUB_STEP_SUMMARY

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        if: steps.filteredChanges.outputs.files != ''
        with:
          run_install: false

      - name: Use NodeJS
        if: steps.filteredChanges.outputs.files != ''
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm

      - name: Find PR
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        if: steps.filteredChanges.outputs.files != ''&& startsWith(github.ref, 'refs/heads/feature/')
        id: prDetails
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          filterOutClosed: true

      - name: Install dependencies
        if: steps.filteredChanges.outputs.files != ''
        run: pnpm install

      - name: Lint files
        if: |
          (
            github.ref == 'refs/heads/develop' ||
            github.ref == 'refs/heads/main'
          ) ||
          (
            steps.filteredChanges.outputs.files != '' &&
            (
              steps.prDetails.outputs.pr_found != 'true' ||
              inputs.node-version != 20
            )
          )
        run: pnpm lint

      - name: Lint files for PR
        if: |
          steps.filteredChanges.outputs.files != '' &&
          steps.prDetails.outputs.pr_found == 'true' &&
          inputs.node-version == 20
        run: pnpm lint:fix

      - name: Commit auto-fixes
        if: |
          always() &&
          steps.filteredChanges.outputs.files != '' &&
          steps.prDetails.outputs.pr_title &&
          inputs.node-version == 20
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ steps.prDetails.outputs.pr_title }} | Files linted"
