name: Lint files

on:
  workflow_call:
  push:
    branches-ignore:
      - main
      - beta
      - alpha

concurrency:
  group: lint-files-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  variables:
    runs-on: self-hosted
    outputs:
      isPrimalBranch: ${{ steps.set-variables.outputs.isPrimalBranch }}
    steps:
      - name: Set variables
        id: set-variables
        run: |
          echo "isPrimalBranch=${{
            github.ref == 'refs/heads/main'
            || github.ref == 'refs/heads/beta'
            || github.ref == 'refs/heads/alpha'
          }}" >> $GITHUB_OUTPUT
  lint-primary:
    needs: variables
    uses: ./.github/workflows/base-eslint-checker.yml
    with:
      fixErrors: ${{ needs.variables.outputs.isPrimalBranch == 'false' }}
      nodeVersion: 20
  lint-rest:
    needs: [variables, lint-primary]
    if: ${{github.event_name == 'push' && needs.variables.outputs.isPrimalBranch == 'false'}}
    uses: ./.github/workflows/base-eslint-checker.yml
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 'latest']
    with:
      fixErrors: false
      nodeVersion: ${{ matrix.node-version }}
