name: Lint files

on:
  workflow_call:
  push:
    branches-ignore:
      - main
      - beta
      - alpha

concurrency:
  group: lint-files-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  print-it:
    runs-on: self-runner-node16
    steps:
      - run: echo ${{ github.event_name }}
  lint-primary:
    uses: ./.github/workflows/base-eslint-checker.yml
    strategy:
      matrix:
        node-version: [20]
    with:
      node-version: ${{ matrix.node-version }}
      is-primary-version: true
  lint-rest:
    if: github.event_name == 'push'
    needs: lint-primary
    uses: ./.github/workflows/base-eslint-checker.yml
    strategy:
      matrix:
        node-version: [16, 18, 'latest']
    with:
      node-version: ${{ matrix.node-version }}
      is-primary-version: false
