name: Lint Projects

on:
  workflow_call:
    inputs:
      isPrimalBranch:
        required: true
        type: boolean

concurrency:
  group: lint-projects-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-primary:
    uses: ./.github/workflows/base-lint.yml
    with:
      fixErrors: ${{ !inputs.isPrimalBranch }}
      nodeVersion: 20
  lint-rest:
    needs: [lint-primary]
    if: ${{github.event_name == 'push' && !inputs.isPrimalBranch}}
    uses: ./.github/workflows/base-lint.yml
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 'latest']
    with:
      fixErrors: false
      nodeVersion: ${{ matrix.node-version }}
